# Generated by Django 4.1.3 on 2022-12-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_remove_member_organisations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='code',
            field=models.CharField(default='AAAAAAAA', max_length=8),
            preserve_default=False,
        ),
    ]
