# Generated by Django 4.1.3 on 2022-12-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
