# Generated by Django 4.1.3 on 2022-12-03 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.member')),
            ],
        ),
    ]
