# Generated by Django 4.1.3 on 2022-12-05 01:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_timesheetentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationmember',
            name='admin',
        ),
        migrations.AlterField(
            model_name='location',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
